### PR TITLE
Support more than one maximized layout in autolayout

### PR DESCRIPTION
**Pull request by luong-komorebi**
First of all, thank you so much. I learn a lot reading your automation codes. 

Secondly, please dismiss this if you dont feel like it suits your need. I understand config files are personal.

In this PR, I want to suggest a change that helps us support more than one maximized layout in autolayout. Take a look and let me know what you think

### CODE REVIEW

**Comment by evantravers** [comment]
@luong-komorebi: I am crazy honored that what I have written is helpful… that makes me very happy this evening!

You are right… I tend to work completely full screen as a matter of principle: trying to maintain focus. However I'm not opposed building something more flexible.

I have been puzzling over this a little bit… adding a bit more flexibility and logic to config seems to be a next step. I'll review your PR a little more closely.

I will give you a hint as to the direction I am thinking about heading… maybe you can hack around and help me get there!

1. I want to support autolayout by window title… I haven't figured this out quite yet, but I often open URLs for video meetings and I want them to go to the monitor under the camera.
2. `hs.layout.apply` has a format for a lua table to describe a layout… you can build up a table and apply it all at once. I think I [do this in autolayout.lua](https://github.com/evantravers/hammerspoon-config/blob/938a4e466494b46a053b205986d9fa085b84c857/autolayout.lua#L46-L58) already…

I'm thinking about replacing `preferred_display` with a table of rules (just like the ones from `hs.layout.apply` I think) for the windows belonging to that app… those could be passed to autolayout.lua to be put together into a layout.

**Comment by evantravers** [comment]
Take a look at this branch @luong-komorebi: https://github.com/evantravers/hammerspoon-config/tree/autolayout-v2 I'll shake it out tomorrow and make sure it works.

**Comment by luong-komorebi** [comment]
Awesome work @evantravers. I believe that your branch autolayout-v2 will be working just fine, covering even broader scope than my little script. I ll close my pull for now, please tag me when you decide to release that or needs code review (spoiler: i m not a Lua guru)

**Comment by luong-komorebi** [comment]
Meanwhile, I m opening this and let's see if we got more layouts to play with. https://github.com/Hammerspoon/hammerspoon/pull/2561

**Comment by evantravers** [comment]
@luong-komorebi glad it helps… I've been working with it and it seems stable, so I'll probably introduce it to master.

I believe `hs.layout` accepts more arguments for that "layout" parameter than the 'hs.layout.right50` style constants. I think those constants basically map to `hs.geometery` values:

```
> hs.layout.right50
hs.geometry.unitrect(0.5,0,0.5,1)
```

So you could directly pass a `hs.geometry` object and that would work too, if you want something more complicated.

I think you could even pass a function (check this @megalithic!) that receives as its argument the window object and returns hs.geometry objects as a result. That may be even cleaner than my current multiple rules implementation.

**Comment by evantravers** [comment]
Yeah… today I think I discovered that my rules system didn't work as expected (I think it just obeys the last rule regardless of matching :( ), and I'm going to try and implement the function method I described earlier.

**Comment by evantravers** [comment]
```
    rules = {
      {nil, 1, hs.layout.left50},
      {"evan", 2, hs.layout.right50},
      {"youtube", 1, hs.layout.maximized}
    }
```

This totally works… so I think this is stable enough to go into master.

**Comment by luong-komorebi** [comment]
Nice. I ll be watching master branch closely

**Comment by luong-komorebi** [comment]
Thank you so much for your effort, @evantravers

**Pull request closed without merging**
